### PR TITLE
added IntelliJ formatter settings

### LINKED ISSUE #39: create shared code formatter for intellij
* create an formatter to use with intellij
* add formatter to repo

### PR DESCRIPTION
**Pull request by matthiasbalke**
This is a first draft of formatter settings, please do not use the formatter before it is merged. Otherwise we'll get a lot of merge conflicts. Once merged I'll format all classes in one PR (closes #39).

### CODE REVIEW

**Comment by matthiasbalke** [comment]
Ready to merge

**Comment by Pentadrago** [comment]
Please add code style settings for TypeScript.

**Comment by matthiasbalke** [comment]
TypeScript settings are already included and matching current style.

**Comment by matthiasbalke** [comment]
please test the formater locally and give feedback on formatting style. In case you both @RudiKlassen, @Pentadrago like it, it can be merged.

**Comment by matthiasbalke** [comment]
added new updated PR with all code formatted

**Pull request merged**
